services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-./deployment}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2024-06-11T03-13-30Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-./deployment}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.5
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-./deployment}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

  mariadb:
    container_name: mariadb
    image: mariadb:11.2.4
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "${MARIA_DB_PASSWORD:-P@ssw0rd}"
      MYSQL_ROOT_PASSWORD: "${MARIA_DB_ROOT_PASSWORD:-P@ssw0rd}"
    ports:
      - "13306:3306"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-./deployment}/volumes/mariadb/data:/var/lib/mysql/data
      - ${DOCKER_VOLUME_DIRECTORY:-./deployment}/volumes/mariadb/logs:/var/lib/mysql/logs
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]

  attu:
    container_name: attu
    image: zilliz/attu:v2.4
    environment:
      MILVUS_URL: 127.0.0.1:19530
    ports:
      - "13000:3000"
    depends_on:
      - "standalone"

  api-backend:
    container_name: api-backend
    image: api-backend
    build:
      context: ./
      dockerfile: ./Dockerfile.api
    ports:
      - "8000:80"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-./deployment}/volumes/api-backend/ml_models:/ml_models

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./
      dockerfile: ./Dockerfile.frontend
    ports:
      - "8080:80"


networks:
  default:
    name: canpolicy_insight